const REGION = "AWS_REGION"; //e.g. "us-east-1"
const TABLE_NAME = "DB_TABLE_NAME";
const AUTH_REGION = "AUTH_AWS_REGION";
const AUTH_API = "AUTH_AWS_API";
const AUTH_STAGE = "AUTH_AWS_STAGE";
const origin = "WEB_ORIGIN";
const LIST_ADMIN_ONLY = LIST_ADMIN_ONLY_VAL;
const DETAILS_ADMIN_ONLY = DETAILS_ADMIN_ONLY_VAL;
const DELETE_ADMIN_ONLY = DELETE_ADMIN_ONLY_VAL;
const INSERT_ADMIN_ONLY = INSERT_ADMIN_ONLY_VAL;
const UPDATE_ADMIN_ONLY = UPDATE_ADMIN_ONLY_VAL;
const SETSCHEMA_ADMIN_ONLY = SETSCHEMA_ADMIN_ONLY_VAL;
const GETSCHEMA_ADMIN_ONLY = GETSCHEMA_ADMIN_ONLY_VAL;

import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
const ddbClient = new DynamoDBClient({ region: REGION });